Menu,Menu,Add,网站文件夹,Function
Menu,网站文件夹,Add,百度,Function
Menu,网站文件夹,Add,虎牙,Function
Menu,网站文件夹,Add,斗鱼,Function
Menu,网站文件夹,Add,ahk中文论坛autoahk,Function
Menu,网站文件夹,Add,ahk官网论坛,Function
Menu,网站文件夹,Add,github,Function
Menu,网站文件夹,Add,卡牌card,Function
Menu,网站文件夹,Add,我的ahk工程,Function
Menu,网站文件夹,Add,超级命令目录,Function
Menu,Menu,Add,ahk,Function
Menu,ahk,Add,帮助手册,Function
Menu,Menu,Add,网站文件夹,:网站文件夹
Menu,Menu,Add,ahk,:ahk
Return